### ISSUE TITLE
License and installation instructions?

### ISSUE THREAD

**Issue by edunham** [mozilla/vaani.iot#4]
It'd be great to add a LICENSE or COPYRIGHT file to this repository to describe how it's ok for others to use the code. 

Additionally, could you please put installation and contributing instructions in the README? The pretty chart is cool, but lacks information about how to get involved and where to engage with the vaani community.

**Comment by kdavis-mozilla** [comment]
This is on purpose as we are not ready for people outside the project to use it yet. When we are ready we will add all the standard info: LICENSE, COPYRIGHT, README...

**Comment by jorgeriv** [comment]
Can you at least add this information about not being ready for people outside the project to get involved yet? I was also looking on how to contribute to the project and it is a bit frustrating to not be able to find any information.

Thanks

**Comment by kdavis-mozilla** [comment]
@jorgeriv Is the README text OK now? If you have any other suggestions, let me know!
